export const gamesList = [
  "Counter-Strike",
  "CoD",
  "Medal Of Honor",
  "Half Life",
  "Doom",
  "Unreal",
  "Halo",
  "Quake",
  "Far Cry",
  "Gears of War",
  "Splatoon",
  "Battlefield",
  "Starcraft",
  "Warcraft",
  "Command&Conq",
  "Age of Empires",
  "Dragon Age",
  "Fallout",
  "Deus Ex",
  "Runescape",
  "Warframe",
  "KoTOR / SWTOR",
  "Tales of",
  "Of Mana",
  "Final Fantasy",
  "Fire Emblem",
  "Pokemon",
  "Chrono",
  "Animal Crossing",
  "Shin Megumi Tensei",
  "Legend of Zelda",
  "Yakuza",
  "Metal Gear",
  "The Sims",
  "Sim City",
  "Rollercoaster Tycoon",
  "MS Flight Sim",
  "Euro/American Truck",
  "Harvest Moon",
  "Cities",
  "Mario",
  "Kirby",
  "Metroid",
  "Portal",
  "Castlevania",
  "Tomb Raider",
  "Uncharted",
  "Donkey Kong",
  "Mega Man",
  "Sonic",
  "Crash Bandicoot",
  "Spyro",
  "Jak & Daxter",
  "Ratchet & Clank",
  "Monkey Island",
  "Ace Attorney",
  "Professor Layton",
  "Zelda",
  "Nancy Drew",
  "FIFA",
  "Madden",
  "NBA",
  "Tony Hawk",
  "Gran Turismo",
  "WiiSports",
  "Rocket League",
  "Football Manager",
  "Punch Out",
  "Guitar / Band Hero",
  "DDR",
  "Just Dance",
  "Singstar",
  "Rhythm Heaven",
  "Civilisation",
  "Europa Universalis",
  "Total War",
  "Crusader Kings",
  "Dark Souls",
  "Kingdom Hearts",
  "Assassins Creed",
  "Elder Scrolls",
  "GTA",
  "Diablo",
  "Borderlands",
  "Monster Hunter",
  "Mass Effect",
  "Red Dead Redemption",
  "God of War",
  "Devil May Cry",
  "Arkham",
  "Fable",
  "Saints Row",
  "Witcher",
  "Street Fighter",
  "Tekken",
  "Smash Bros",
  "Mortal Kombat",
  "Doki Doki Literature Club",
  "I Love You",
  "Colonel Sanders",
  "999",
  "The Walking Dead",
  "Dark Pictures",
  "Overwatch",
  "DotA",
  "World of Tanks",
  "Among Us",
  "Fortnite",
  "Worms",
  "Minecraft",
  "League of Legends",
  "Team Fortress",
  "PUBG",
  "Bloons TD",
  "Orcs Must Die!",
  "Dungeon Defenders",
  "Plants Vs Zombies",
  "Resident Evil",
  "Dead Space",
  "Little Nightmares",
  "Parasite Eve",
  "Five nights at Freddys",
  "Pac-Man",
  "Galaga",
  "Space Invaders",
  "Pong",
  "Frogger",
  "Contra",
  "Ikaruga",
  "Overcooked",
  "You Dont Know Jack",
  "Xcom",
  "Heroes of Might and Magic",
  "Teamfight Tactics",
  "Heathstone",
  "Bejeweled / Candy Crush",
  "Tetris",
  "Clash Royale / Clash of Clans",
  "Evony",
  "Snake",
  "Lego",
  "Dynasty Warriors",
  "Nintendogs",
  "Terraria",
  "Flappy Bird",
];
